language: scala

scala:
  - 2.13.1

jdk:
  - openjdk11

sudo: required
dist: trusty

script:
  - git config --global user.email "gabrielasman10@gmail.com"
  - git config --global user.name "gabrielasman"
  - echo $GCP_TOKEN | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
  - sbt 'release with-defaults'

